/** All navigable screens. Game ids match the registry. */
export type Route =
  | 'main'
  | 'languages'
  | 'lang-menu'
  | 'practice'
  | 'recap'
  | 'statistics'
  | 'store'
  | 'settings'
  | 'account'
  | 'subscription'
  | 'reset'
  | 'learn'
  | 'fill-in-the-blanks'
  | 'grammar'
  | 'recap-cipher'
  | 'recap-grammar'
  | 'recap-crossword'
  | 'challenge';
