/**
 * Crossword clues: a cryptic / definitional German clue plus its English
 * equivalent for every vocabulary word. The crossword board shows the German
 * clue by default with a DE/EN toggle. Keyed by word-id; falls back to the
 * plain gloss if a word ever lacks a clue.
 */
import { wordById } from './vocab';

export interface Clue {
  de: string;
  en: string;
}

export const CLUES: Record<string, Clue> = {
  "w-der": { de: "Maskuliner Artikel", en: "Masculine 'the'" },
  "w-ist": { de: "'Sein' für er/sie/es", en: "'to be' for he/she/it" },
  "w-mann": { de: "Ein erwachsener Mensch, männlich", en: "An adult male person" },
  "w-gut": { de: "Nicht schlecht", en: "Not bad" },
  "w-gross": { de: "Nicht klein", en: "Not small" },
  "w-die": { de: "Femininer Artikel", en: "Feminine 'the'" },
  "w-frau": { de: "Ein erwachsener Mensch, weiblich", en: "An adult female person" },
  "w-schoen": { de: "Sehr hübsch anzusehen", en: "Lovely to look at" },
  "w-und": { de: "Verbindet Wörter: Hunde ___ Katzen", en: "Joins words: dogs ___ cats" },
  "w-auch": { de: "Ebenso, genauso", en: "As well, too" },
  "w-das": { de: "Neutraler Artikel", en: "Neuter 'the'" },
  "w-kind": { de: "Ein junger Mensch", en: "A young person" },
  "w-klein": { de: "Nicht groß", en: "Not big" },
  "w-sehr": { de: "Verstärkt: ___ gut", en: "Intensifier: ___ good" },
  "w-nicht": { de: "Verneinung", en: "Negation (not)" },
  "w-ich": { de: "Erste Person: ___ bin", en: "First person: ___ am" },
  "w-bin": { de: "'Sein' für ich", en: "'to be' for I" },
  "w-du": { de: "Zweite Person (informell)", en: "Second person (informal you)" },
  "w-bist": { de: "'Sein' für du", en: "'to be' for you" },
  "w-muede": { de: "Braucht Schlaf", en: "Needs sleep" },
  "w-ein": { de: "Unbestimmter Artikel (m/n)", en: "Indefinite article (a)" },
  "w-hund": { de: "Ein Haustier, das bellt", en: "A pet that barks" },
  "w-hat": { de: "'Haben' für er/sie/es", en: "'to have' for he/she/it" },
  "w-einen": { de: "Unbestimmter Artikel im Akkusativ", en: "'a' (accusative)" },
  "w-garten": { de: "Grüner Bereich am Haus", en: "Green space by the house" },
  "w-haus": { de: "Ein Gebäude zum Wohnen", en: "A building you live in" },
  "w-neu": { de: "Nicht alt", en: "Not old" },
  "w-alt": { de: "Nicht neu", en: "Not new" },
  "w-hier": { de: "An diesem Ort", en: "At this place" },
  "w-heute": { de: "Dieser Tag", en: "This day (today)" },
  "w-katze": { de: "Ein Haustier, das miaut", en: "A pet that meows" },
  "w-eine": { de: "Unbestimmter Artikel (feminin)", en: "'a' (feminine)" },
  "w-auto": { de: "Ein Fahrzeug mit vier Rädern", en: "A vehicle with four wheels" },
  "w-schnell": { de: "Mit hoher Geschwindigkeit", en: "At high speed" },
  "w-langsam": { de: "Nicht schnell", en: "Not fast" },
  "w-wir": { de: "Ich und andere", en: "Me and others (we)" },
  "w-sind": { de: "'Sein' für wir/sie", en: "'to be' for we/they" },
  "w-ihr": { de: "Mehrere 'du'", en: "You (plural)" },
  "w-seid": { de: "'Sein' für ihr", en: "'to be' for you (pl.)" },
  "w-gluecklich": { de: "Voller Freude", en: "Full of joy" },
  "w-trinkt": { de: "Nimmt ein Getränk zu sich", en: "Has a drink" },
  "w-wasser": { de: "Klares Getränk ohne Geschmack", en: "A clear, plain drink" },
  "w-kaffee": { de: "Warmes Getränk, das wach macht", en: "A hot drink that wakes you up" },
  "w-gern": { de: "Mit Freude: etwas ___ tun", en: "Gladly, with pleasure" },
  "w-tee": { de: "Heißes Getränk aus Blättern", en: "A hot drink made from leaves" },
  "w-buch": { de: "Hat Seiten, man liest es", en: "It has pages; you read it" },
  "w-liest": { de: "Schaut Wörter in einem Buch an", en: "Looks at words in a book" },
  "w-interessant": { de: "Macht neugierig, spannend", en: "Makes you curious" },
  "w-oder": { de: "Tee ___ Kaffee?", en: "Tea ___ coffee?" },
  "w-aber": { de: "Klein, ___ stark", en: "Small, ___ strong" },
  "w-apfel": { de: "Eine Frucht, oft rot oder grün", en: "A fruit, often red or green" },
  "w-isst": { de: "Nimmt Essen zu sich", en: "Has food" },
  "w-brot": { de: "Der Bäcker backt es", en: "The baker bakes it" },
  "w-jetzt": { de: "In diesem Moment", en: "At this moment" },
  "w-oft": { de: "Viele Male", en: "Many times" },
  "w-stadt": { de: "Großer Ort mit vielen Häusern", en: "A big place with many houses" },
  "w-wohnt": { de: "Lebt an einem Ort", en: "Lives at a place" },
  "w-schule": { de: "Kinder lernen dort", en: "Children learn there" },
  "w-lehrer": { de: "Unterrichtet in der Schule", en: "Teaches at school" },
  "w-freund": { de: "Eine Person, die man mag", en: "A person you like" },
  "w-kommt": { de: "Bewegt sich hierher", en: "Moves toward here" },
  "w-geht": { de: "Bewegt sich zu Fuß weg", en: "Walks away" },
  "w-immer": { de: "Zu jeder Zeit", en: "At all times" },
  "w-nie": { de: "Zu keiner Zeit", en: "At no time" },
  "w-bald": { de: "In kurzer Zeit", en: "In a short while" },
  "w-er": { de: "Dritte Person, männlich", en: "Third person, male (he)" },
  "w-sie": { de: "Dritte Person, weiblich", en: "Third person, female (she)" },
  "w-es": { de: "Dritte Person, neutral", en: "Third person, neuter (it)" },
  "w-macht": { de: "'Tun' für er/sie/es", en: "Makes or does" },
  "w-was": { de: "Frage nach einer Sache", en: "Asks about a thing (what)" },
  "w-wer": { de: "Frage nach einer Person", en: "Asks about a person (who)" },
  "w-wie": { de: "Frage nach der Art", en: "Asks how" },
  "w-wo": { de: "Frage nach dem Ort", en: "Asks where" },
  "w-wann": { de: "Frage nach der Zeit", en: "Asks when" },
  "w-warum": { de: "Frage nach dem Grund", en: "Asks why" },
  "w-eins": { de: "Die Zahl 1", en: "The number 1" },
  "w-zwei": { de: "Die Zahl 2", en: "The number 2" },
  "w-drei": { de: "Die Zahl 3", en: "The number 3" },
  "w-vier": { de: "Die Zahl 4", en: "The number 4" },
  "w-fuenf": { de: "Die Zahl 5", en: "The number 5" },
  "w-moechte": { de: "Hätte gern, wünscht sich", en: "Would like" },
  "w-tisch": { de: "Möbel, man isst daran", en: "Furniture you eat at" },
  "w-stuhl": { de: "Möbel zum Sitzen", en: "Furniture for sitting" },
  "w-kauft": { de: "Bezahlt für etwas im Laden", en: "Pays for something in a shop" },
  "w-teuer": { de: "Kostet viel Geld", en: "Costs a lot" },
  "w-billig": { de: "Kostet wenig Geld", en: "Costs little" },
  "w-warm": { de: "Angenehm heiß", en: "Pleasantly hot" },
  "w-kalt": { de: "Nicht warm", en: "Not warm" },
  "w-wetter": { de: "Sonne, Regen, Wind …", en: "Sun, rain, wind …" },
  "w-sonne": { de: "Sie scheint am Himmel", en: "It shines in the sky" },
  "w-spielt": { de: "Macht ein Spiel, hat Spaß", en: "Plays a game" },
  "w-park": { de: "Grüner Ort in der Stadt", en: "A green place in the city" },
  "w-ball": { de: "Rund, man spielt damit", en: "Round; you play with it" },
  "w-mit": { de: "Zusammen ___ jemandem", en: "Together ___ someone" },
  "w-dem": { de: "Artikel im Dativ", en: "'the' (dative)" },
  "w-uebrigens": { de: "Nebenbei gesagt", en: "By the way" },
  "w-irgendwie": { de: "Auf eine unklare Art", en: "In some way, somehow" },
  "w-wirklich": { de: "Tatsächlich, echt", en: "Truly, really" },
  "w-nur": { de: "Nicht mehr als das", en: "No more than; only" },
  "w-schon": { de: "Früher als erwartet", en: "Already, sooner than expected" },
  "w-in": { de: "___ der Stadt", en: "___ the city" },
  "w-noch": { de: "Immer ___ hier", en: "Still" },
  "w-dann": { de: "Danach, zu der Zeit", en: "Then, after that" },
  "w-leider": { de: "Unglücklicherweise", en: "Unfortunately" },
  "w-vielleicht": { de: "Möglich, aber nicht sicher", en: "Maybe, possibly" },
};

export function clueFor(wordId: string, lang: 'de' | 'en'): string {
  const c = CLUES[wordId];
  if (!c) return wordById(wordId)?.en ?? wordId;
  return lang === 'de' ? c.de : c.en;
}
